# Generated by Django 3.1.1 on 2020-09-27 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8, 'Your password should have at least 8 characters')])),
                ('is_Admin', models.BooleanField()),
            ],
        ),
    ]
